### ISSUE TITLE
Ramps toward the end are not equally distanced on the chart

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#343] opened 2018-09-22 11:35 UTC
Example from https://nus-cs2103-ay1819s1.github.io/cs2103-dashboard

![image](https://user-images.githubusercontent.com/1673303/45916790-233b5000-be9e-11e8-93fa-c5ba3b5958a1.png)

This ramp representing a commit on 20th is shown at the edge of bar but the edge of the bar should be 21st? Either the 21st is missing from the chart area or the ramp is appearing in the wrong day.

**Comment by damithc** [comment] 2018-09-22 14:05
Looks like the width of the graph is chosen by the date of the last commit. A better choice is for it to be the last day under analysis, which is _today_.

**Comment by eugenepeh** [comment] 2018-09-22 15:48
> This ramp representing a commit on 20th is shown at the edge of bar but the edge of the bar should be 21st? Either the 21st is missing from the chart area or the ramp is appearing in the wrong day.

Actually we argued about the rationale of this before. In both github url params and git blame functionality, `until` denotes the end of the analysis. E.g. since 2018-09-20 to until 2018-09-21 will only chunk out the 24 hours worth of result instead of 48 hours.

**Comment by jamessspanggg** [comment] 2019-07-08 02:55
@damithc Can you reproduce this error again? I have tried and this error does not appear anymore.

**Comment by damithc** [comment] 2019-07-08 03:05
> * Also, if no end point is specified, all commits upto the current moment should be captured; should not stop at previous day midnight.

Can you check if this is the case?

> * Anyway, I got the impression that the chart shows only up to the last day a contribution was made. i.e., if no contribution was made after last Monday, the graph shows only upto last Monday. Do check if that is the case. If that is indeed the case, that need fixing too.

This is already fixed.

**Comment by jylee-git** [comment] 2019-07-08 03:16
> > * Also, if no end point is specified, all commits upto the current moment should be captured; should not stop at previous da midnight.
> y
> Can you check if this is the case?

Yes, as of now, end point will default to date of report generation at 23:59.

**Comment by jylee-git** [comment] 2019-07-08 03:16
Closing issue as this has already been fixed

**Closed by jylee-git** 2019-07-08 03:16 UTC
Labels: a-FrontEnd, c.Bug, p.High
