### ISSUE TITLE
Possibility of Regression Bug

### ISSUE THREAD

**Issue by Tejas2805** [reposense/RepoSense#1244] opened 2020-04-19 07:08 UTC
The Travis build which hadn't been failing upto 3 days ago, has started failing. This is when we started merging all the PRs again. We might have a regression bug. Let's look into this and find out the reason.

Can check the travis build [here](https://travis-ci.org/github/nus-cs2103-AY1920S2/ip-dashboard/builds).

This is related to individual project dashboard for CS2103T

**Comment by Tejas2805** [comment] 2020-04-19 07:18
Could have been due to #1050 or #1189 . Other PRs seem unlikely.

**Comment by Tejas2805** [comment] 2020-04-19 07:19
@ang-zeyu @jamessspanggg Could you guys take a look into this.

**Comment by jamessspanggg** [comment] 2020-04-19 08:01
On first glance, it is due to the student having a file name called `..\data\duke.txt`, which leads to the file not being matched in the `isFileGlobMatching` method. Don't think it's due to any of our recent PRs merged as we did not touch the functionality of the file matching. [Student's repo](https://github.com/EdmondOng/duke)
<img width="1013" alt="Screen Shot 2020-04-19 at 3 58 38 PM" src="https://user-images.githubusercontent.com/32864116/79682670-a4afbb80-8256-11ea-9bc8-830b801e031f.png">

Will investigate further.

**Comment by jamessspanggg** [comment] 2020-04-19 08:52
@Tejas2805 can you inform the prof to temporarily fix the issue by adding `..\data\duke.txt` in the Ignore Glob List column of `https://github.com/EdmondOng/duke.git` in `author-config.csv`?

**Comment by damithc** [comment] 2020-04-19 09:14
> @Tejas2805 can you inform the prof to temporarily fix the issue by adding `..\data\duke.txt` in the Ignore Glob List column of `https://github.com/EdmondOng/duke.git` in `author-config.csv`?

Which repo? Can do a PR?

**Comment by jamessspanggg** [comment] 2020-04-19 09:17
> Which repo? Can do a PR?

Created a PR here: https://github.com/nus-cs2103-AY1920S2/ip-dashboard/pull/1

**Comment by damithc** [comment] 2020-04-19 09:29
Actually, that will update that semester's dashboard which is supposed to frozen in time at the end of that semester. At lease we should also add an end-date the CLI parameters to prevent it analyzing repos until today. Also, the PR fails the build.

**Comment by Tejas2805** [comment] 2020-04-19 10:41
I thought it could be due to the same file too, but the thing is the file has been there from before. Therefore, that shouldn't have been the cause of the build to fail.

**Comment by Tejas2805** [comment] 2020-04-19 11:00
> Also, the PR fails the build.

The build hasn't failed due to the initial reason. But the same error at a different repo.

**Comment by jamessspanggg** [comment] 2020-04-19 11:34
The problem is due to **_git specifically prints out filename surrounded by double quotes_**, if the filename contains any special characters (in this bug's case, it is due to the special character "\"). I have tested the behaviour, and an example is shown below:

<img width="1145" alt="Screen Shot 2020-04-19 at 7 27 58 PM" src="https://user-images.githubusercontent.com/32864116/79686659-abe5c200-8274-11ea-9d71-5bbd2e13d3df.png">

Will issue a fix soon.

**Comment by Tejas2805** [comment] 2020-04-19 11:43
Ah I see. Is it some new update though? As initially it wasn't failing.

**Comment by jamessspanggg** [comment] 2020-04-19 15:49
> Ah I see. Is it some new update though? As initially it wasn't failing.

I'm not so sure, I tried checking out to the version of the last successful Travis build (commit 0f57aab1de) and ran the same build, and there were still errors. 

> The problem is due to git specifically prints out filename surrounded by double quotes

Still need some time to figure out the bugs, as the one described above is not the only issue. Would appreciate it if we can investigate together.

**Comment by jamessspanggg** [comment] 2020-04-20 04:02
Update: the bug is due to #1192 not handling files with names that are automatically escaped and double quoted by GitHub. For e.g. file name `..\data\duke.txt` -> `"..\\data\\duke.txt"`.

Upon investigating further, the code in `FileInfoExtractor#getEditedFileInfos` also made the same mistake of not handling this case, but not reflected in the bug as they simply skip the processing of these files when not matched with their regex.

**Closed** 2020-04-20 08:51 UTC
Labels: c.Bug, c.Investigate, p.High
