### ISSUE TITLE
Some CS2103 commits not showing up in the reposense dashboard

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1533] opened 2021-04-09 08:33 UTC
Bug reported by student https://github.com/nus-cs2103-AY2021S2/forum/issues/302
Config https://github.com/nus-cs2103-AY2021S2/tp-dashboard/tree/master/configs
Dashboard https://nus-cs2103-ay2021s2.github.io/tp-dashboard
[Commits by author](https://nus-cs2103-ay2021s2.github.io/tp-dashboard/?search=w14&sort=groupTitle&sortWithin=title&since=2021-02-19&timeframe=commit&mergegroup=&groupSelect=groupByRepos&breakdown=false&tabOpen=true&tabType=zoom&zA=noelmathewisaac&zR=AY2021S2-CS2103T-W14-4%2Ftp%5Bmaster%5D&zACS=222.4375&zS=2021-02-19&zFS=w14&zU=2021-04-10&zMG=undefined&zFTF=commit&zFGS=groupByRepos&zFR=false) (`noelmathewisaac`)

Need to fix quickly if this is a real problem

**Comment by damithc** [comment] 2021-04-10 02:54
@gerhean @dcshzj @HCY123902 need help with this

**Comment by HCY123902** [comment] 2021-04-10 04:15
After trying it locally, removing `src/main/resources` in the `Ignore Glob List` column in `repo-config.json` seems to make the report include commits that only involves changes with Fxml and CSS files. The possible cause of the original problem is that these files resides in `src/main/resources` and the changes made to them are not recognized by the report

**Comment by damithc** [comment] 2021-04-10 04:22
Thanks for the investigation @HCY123902 
How come .fxml files still appear in the code view? Perhaps 'ignore glob' is not working fully?

**Comment by HCY123902** [comment] 2021-04-10 04:50
I think using `src/main/resources/**` instead of `src/main/resources` will remove the Fxml file changes and commits that only involves Fxml and CSS files from the report, which should give the intended behavior. The current issue seems to be that, when path glob such as `src/main/resources` is used in the column, some file changes in the path glob are still captured by the authorship contribution panel, but the commits that only involve changes in the file path glob will be ignored by the report. Maybe the documentation should include the file path glob format specification in the CSV configuration?

**Comment by damithc** [comment] 2021-04-10 04:56
> I think using `src/main/resources/**` instead of `src/main/resources` will remove the Fxml file changes and commits that only involves Fxml and CSS files from the report, which should give the intended behavior. The current issue seems to be that, when path glob such as `src/main/resources` is used in the column, some file changes in the path glob are still captured by the authorship contribution panel, but the commits that only involve changes in the file path glob will be ignored by the report. Maybe the documentation should include the file path glob format specification in the CSV configuration?

Thanks for the further investigation @HCY123902 
Yes, we can update the documentation if necessary.

**Comment by gerhean** [comment] 2021-04-10 05:34
Should we remove `src/main/resources/view` from the Ignore Glob List? So something like `src/main/resources/!(view)/**`

**Comment by damithc** [comment] 2021-04-10 06:31
> Should we remove `src/main/resources/view` from the Ignore Glob List? So something like `src/main/resources/!(view)/**`?

Can try that. Confirmed that's the correct glob syntax?

**Comment by damithc** [comment] 2021-04-10 07:06
> > Should we remove `src/main/resources/view` from the Ignore Glob List? So something like `src/main/resources/!(view)/**`?
> 
> Can try that. Confirmed that's the correct glob syntax?

Seems to work. Thanks for the top @gerhean 
We can add a few examples like these in the documentation.

**Comment by gerhean** [comment] 2021-04-10 07:48
I just assumed that it was the same as the frontend minimatch, but I can't say for sure.

**Comment by damithc** [comment] 2021-04-10 08:25
> Also I think `src/main/resources/!(view)/**` does not match files placed directly in the resource folder (means reposense will not ignore them), not sure if that's important.

I'm also not sure if this expression is a good fit, although doesn't seem to break anything ATM. 
In any case, we should provide better documentation of glob patterns supported. 
Might depend on the libraries used by the frontend and backend as globs are used in both parts.

**Comment by gerhean** [comment] 2021-04-10 09:33
This is fairly comprehensive https://mywiki.wooledge.org/glob

**Comment by damithc** [comment] 2021-04-10 09:37
> This is fairly comprehensive https://mywiki.wooledge.org/glob

Nice. Let's point to it from our UG.

**Comment by HCY123902** [comment] 2021-04-10 10:08
Actually, there is already a link in User Guide pointing to https://docs.oracle.com/javase/tutorial/essential/io/fileOps.html#glob

**Comment by HCY123902** [comment] 2021-04-10 10:11
@gerhean Do you mind if I start a PR on it? I think it is just a minor change that adds some link to the User Guide

**Comment by dcshzj** [comment] 2021-04-27 02:53
#1541 has been merged, any other tasks still pending for this issue?

**Comment by yhtMinceraft1010X** [comment] 2023-01-27 10:48
Propose closing this issue since the [corresponding issue](https://github.com/nus-cs2103-AY2021S2/forum/issues/302) in the CS2103 forum for that semester has also been closed (and something from 2 years back is unlikely to be relevant today).

**Comment by chan-j-d** [comment] 2023-01-27 14:01
I agree, think we can close the issue

**Closed by chan-j-d** 2023-01-27 14:01 UTC
Labels: p.Low
