### ISSUE TITLE
Restoring not working properly for zoom panel

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1486] opened 2021-03-19 14:33 UTC
**Tell us about your environment**

* **RepoSense Version:**master
* **OS and Version:**Windows10
* **Web Browser and Version (if applicable):**Edge

**Please include the steps to reproduce the bug.**

1. Open the zoom panel of an individual author
1. Merge the group and open the group zoom panel
1. Reload the page 

**What was expected to happen?**
The zoom panel of the merged group should be shown on the screen

**What actually happened? Please include a screenshot of the output.**
The zoom panel of an individual author is shown

![image](https://user-images.githubusercontent.com/54735123/111796371-12e77d00-8903-11eb-8299-529ed0761a57.png)

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by gerhean** [comment] 2021-03-20 16:27
Bug is actually a regression due to #1457 changing only some instances of isMerge to isMerged.

The only real change which needs to be made is to rename all isMerge to isMerged, and:

v_summary_charts.js line 178:
from
`zAuthor: user.name,`
to
`zAuthor: isMerged ? '' : user.name,`
which I believe is the reasonable change to make as there should not be an author when the group is merged.

**Closed** 2021-04-13 04:55 UTC
Labels: c.Bug, d.Contributors
