### ISSUE TITLE
Warnings in the log

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1463] opened 2021-03-07 06:53 UTC
Refer to the following warnings:

![image](https://user-images.githubusercontent.com/1673303/110231751-8dec8300-7f54-11eb-8b8a-5b4ddd3e118d.png)

https://github.com/nus-cs2103-AY2021S2/tp-dashboard/runs/2048437170?check_suite_focus=true

Are they necessary? At least some of them don't seem necessary e.g., ones caused by case difference

**Comment by fzdy1914** [comment] 2021-03-07 06:56
I doubt they have used an improper standalone config though.

**Comment by damithc** [comment] 2021-03-07 07:03
> I doubt they have used an improper standalone config though.

I don't think so. These warnings show up at the very beginning when I set up the dashboard (not enough time or reason for students to add stand alone configs). These could be cases where the student configured the GitHub username to be Git username as well, but the two differ in upper/lower case.

**Comment by Tejas2805** [comment] 2021-03-07 08:34
The issue occurs because in the configs the same aliases are found for two different usernames. We don't look for case difference, and just duplicates and that's why even if the difference is just case, the issue persists.

**Comment by damithc** [comment] 2021-04-04 15:36
I think it's best to remove it (i.e., do a case-insensitive match) as it can be confusing to the user.

**Comment by FH-30** [comment] 2021-07-28 18:04
Hi prof @damithc, when diving into the code actually the reason why the warnings occur is due to case insensitivity (though this behavior is actually necessary). The warnings occurs due to the following code flow:
* ```processLine``` method in ```AuthorConfigCsvParser.java``` executes ```config.addAuthor(author);```
* ```addAuthor``` method in ```AuthorConfiguration.java``` executes ```setAuthorDetails(author);```
* ```setAuthorDetail``` method in ```AuthorConfiguration.java``` executes ```addAuthorDetailsToAuthorMapEntry(author, Arrays.asList(author.getGitId()));``` followed by ```addAuthorDetailsToAuthorMapEntry(author, author.getAuthorAliases());``` as shown below:
![Screen Shot 2021-07-29 at 1 32 01 AM](https://user-images.githubusercontent.com/61911161/127369359-d0a5845c-3aaa-4d4b-9296-81276db7ed26.png)

Now let us take the warning for wei-yutong as an example from the image below:
![here](https://user-images.githubusercontent.com/1673303/110231751-8dec8300-7f54-11eb-8b8a-5b4ddd3e118d.png)

From the discussion above it seems you might have misunderstood that wei-yutong's warning is "relevant" because it isn't due to a case-sensitive issue but actually on closer inspection it is also due to case-sensitiveness.

If you inspect the ```author-config.csv``` fed into RepoSense that generated the warnings above [here](https://user-images.githubusercontent.com/1673303/110231751-8dec8300-7f54-11eb-8b8a-5b4ddd3e118d.png), and search for wei-yutong, you will find this:
![Screen Shot 2021-07-29 at 1 37 11 AM](https://user-images.githubusercontent.com/61911161/127370046-526fc8f3-68b8-4054-a05a-5edadd425a7f.png)
From analyzing the csv above (or intelli j's debugger) this results in:
* ```author.getGitId()``` returning ```wei-yutong```
* ```author.getAuthorAliases() ``` returning a list containing ```Wei Yutong``` and ```wei yutong```

Now let us examine the ```addAuthorDetailsToAuthorMapEntry``` closer:
![Screen Shot 2021-07-29 at 1 30 28 AM](https://user-images.githubusercontent.com/61911161/127369142-d79c5018-525d-40b9-9524-5a477d6f1119.png)

The internals of the ```checkDuplicateAliases``` method in the image above is shown below for ease:
![Screen Shot 2021-07-29 at 1 46 14 AM](https://user-images.githubusercontent.com/61911161/127371200-7f34349b-1c94-4cbb-bab5-b40c3c5dca11.png)

The execution ```addAuthorDetailsToAuthorMapEntry(author, Arrays.asList(author.getGitId()));``` populates ```authorDetailsToAuthorMap``` in ```AuthorConfiguration.java``` with the key ```wei-yutong```. Nothing is logged here as ```authorDetailsToAuthorMap.containsKey(alias)``` returns false (which makes sense as ```wei-yutong``` has yet to exist in ```authorDetailsToAuthorMap```).

The next line executed: ```addAuthorDetailsToAuthorMapEntry(author, author.getAuthorAliases());``` results in ```Wei Yutong``` being added as a key in ```authorDetailsToAuthorMap```. Again nothing is logged as ```Wei Yutong``` is not the same as ```wei-yutong``` so ```authorDetailsToAuthorMap.containsKey(alias)``` returns false.

Still executing this line ```addAuthorDetailsToAuthorMapEntry(author, author.getAuthorAliases());```, now ```wei yutong``` is attempted to be added as a key to ```authorDetailsToAuthorMap``` however, ```authorDetailsToAuthorMap.containsKey(alias)``` returns true so it logs the warning indicating that this alias will be ignored.

Now it is indeed peculiar why ```authorDetailsToAuthorMap.containsKey(alias)``` returns true because a regular map should be case sensitive. The image below shows how ```authorDetailsToAuthorMap``` is declared:
![Screen Shot 2021-07-29 at 1 56 51 AM](https://user-images.githubusercontent.com/61911161/127372540-c5335ee7-4b2f-4365-9151-2609662cda93.png)
Upon testing a TreeMap with this comparator, it turns out this TreeMap has a different behavior as compared to a regular one. This TreeMap 's ```containsKey``` method is case insensitive when it comes to strings. 

However, this variant of TreeMap has to be "preserved" because this TreeMap allows for the put method of the map here:
![Screen Shot 2021-07-29 at 2 00 45 AM](https://user-images.githubusercontent.com/61911161/127373047-452ba92a-f70e-4fcb-8379-fdf24fe2d14d.png)
to elegantly "ignore" the key being inserted (not sure if this necessary though).

You can refer to this peculiar TreeMap's behavior here:
![Screen Shot 2021-07-29 at 2 03 06 AM](https://user-images.githubusercontent.com/61911161/127373313-b242e67d-0b95-4ca1-a547-821196d5d261.png)

This concludes my investigation into the issue.

**Comment by FH-30** [comment] 2021-07-28 18:05
@damithc do inform me if you want any changes to the current implementation of the log above after reading my comment above, I will be happy to assist!

**Comment by damithc** [comment] 2021-07-29 02:44
@FH-30 thanks very much for the investigation. Can you also frame your findings in this way?
* Anything needs changing?
* Alternative ways of changing, and their pros/cons

**Comment by FH-30** [comment] 2021-07-30 10:21
Prof @damithc, 

Before reading my reply to your questions, do take note of this:
 ```authorDetailsToAuthorMap``` in ```AuthorConfiguration.java``` is used only in ```AnnotatorAnalyzer.java``` (This file contains methods for implementing the @@author annotation feature of RepoSense). 

* In my opinion, it will be good to remove ```String.CASE_INSENSITIVE_ORDER``` from the instance of ```authorDetailsToAuthorMap``` in ```AuthorConfiguration.java``` as shown below:
![](https://user-images.githubusercontent.com/61911161/127372540-c5335ee7-4b2f-4365-9151-2609662cda93.png)

Justification is as follows

Current behavior of RepoSense:
|```Author's GitHub ID``` column in ```author-config.csv``` | ```Author's Git Author Name``` column in ```author-config.csv``` | Content of ```authorDetailsToAuthorMap``` (In chronological order)|
|--------------------------------------------------|----------------|-----------------------|
|FH-30|Francis Hodianto|{FH-30 -> FH-30 author object, Francis Hodianto -> FH-30 author object}|
|Anonymous|fh-30|{FH-30 -> Anonymous author object, Francis Hodianto -> FH-30 author object, Anonymous -> Anonymous author object}|

This results in the following scenario:
A user of RepoSense uses @@FH-30 to refer to the Author FH-30 writing the code block beneath it. However, if you see the content of ```authorDetailsToAuthorMap``` above, @@FH-30 will result in the code block being assigned to author Anonymous instead.

Aside from the "odd behavior" above, the log message generated also doesn't really make sense as shown below:
```Duplicate alias fh-30 found. The alias will belong to the last author - Anonymous```. From the user's perspective, ```FH-30``` is not the same as ```fh-30``` and such a log message will throw him/her off. This log message also does not justify to the user the behavior in the scenario above as based on reading the log message the user will not expect any change to ```FH-30```'s assigned author but only to ```fh-30```.

Behavior of RepoSense if  ```String.CASE_INSENSITIVE_ORDER``` is removed:
|```Author's GitHub ID``` column in ```author-config.csv``` | ```Author's Git Author Name``` column in ```author-config.csv``` | Content of ```authorDetailsToAuthorMap``` (In chronological order)|
|--------------------------------------------------|----------------|-----------------------|
|FH-30|Francis Hodianto|{FH-30 -> FH-30 author object, Francis Hodianto -> FH-30 author object}|
|Anonymous|fh-30|{FH-30 -> FH-30 author object, Francis Hodianto -> FH-30 author object, fh-30 -> Anonymous author object, Anonymous -> Anonymous author object}|

Now with this change, if a user uses @@FH-30 it will correctly refer to the Author FH-30. No log message will be logged either.

However, there is still a scenario where the behavior of the current and fixed implementation can be odd as shown below:
|```Author's GitHub ID``` column in ```author-config.csv``` | ```Author's Git Author Name``` column in ```author-config.csv``` | Content of ```authorDetailsToAuthorMap``` (In chronological order)|
|--------------------------------------------------|----------------|-----------------------|
|FH-30|Francis Hodianto|{FH-30 -> FH-30 author object, Francis Hodianto -> FH-30 author object}|
|Anonymous|FH-30|{FH-30 -> Anonymous author object, Francis Hodianto -> FH-30 author object, Anonymous -> Anonymous author object}|

Logged message:
```Duplicate alias FH-30 found. The alias will belong to the last author - Anonymous```

Now if the user of RepoSense sees the log message he'll understand why. But now consider that ```Anonymous``` and ```FH-30``` are taking ```CS2103T``` using the @@author feature of RepoSense. The students don't know anything about the author-config.csv nor about the log messages. Everytime ```FH-30``` writes code, he'll assign it to himself using @@author FH-30. However because of the same FH-30 alias of Anonymous, it'll be assigned to anonymous instead.

We might need a way to handle cases where aliases and gitID's of different authors are the same to prevent such scenarios. (Nothing comes to mind for now, maybe prof @damithc can give a suggestion if you think this is worth addressing)

*alternative implementations:
Leave it as it is
Pros:
- Nothing needs to be done
Cons:
- If such scenarios like discussed above do happen, then it'll be confusing to the users.

**Comment by damithc** [comment] 2021-07-30 11:23
@FH-30 Sorry, I wasn't clear earlier. My question should have been, from the _external behavior_ point of view, what are the options, pros/cons? Can you separate out that part? Reason: my inputs are usually w.r.t. external behavior only.

The decisions w.r.t. internal implementation details need to be taken by the senior devs. I might be able to comment on them at a higher level, but I'm not familiar enough with the implementation details to give an authoritative decision on that front.

So, we need to separate out these two aspects so that the appropriate parties can get involved in the decision process.

**Comment by FH-30** [comment] 2021-07-30 16:41
@damithc thanks prof for rephrasing the question.

We have two options as to how to proceed with the implementation:

To note: changes in code concerning when the above log occurs will affect the behavior of ```@@author <name>``` feature of RepoSense (they are linked due to how RepoSense is currently implemented).

* We can leave it as it is
pros:
-No need for code change
-Scenarios where it can go wrong (will elaborate below) is rare (might not happen in real life when using)
cons:
-If the scenarios do happen, there might be issues opened in the future when it can actually be prevented now

* Change the type of ```TreeMap``` assigned to ```authorDetailsToAuthorMap``` (the TreeMap checked to decide whether to log the warning). Change it from being case insensitive to case sensitive.
pros:
-eliminate certain scenarios (which might be potential issues in the future)
cons:
-need code change

The scenario I refer to above is as follows:
In ```author-config.csv``` we add two authors:
1. Author with GithubId FH-30
2. Author with GithubId Anonymous and git name (alias) fh-30

The warning logged:
```Duplicate alias fh-30 found. The alias will belong to the last author - Anonymous```.

Now when this happens, whenever the repository consisting the two authors above are analyzed and the actual author FH-30 uses ```@@author FH-30``` wherever he writes code to mark it as his, it will be assigned to Anonymous instead.

Reading the warning logged also does not explain anything to the user because from the user's perspective, ```FH-30``` is different from ```fh-30``` so by reading the warning the user will only assume that ```@@author fh-30``` will be assigned to Anonymous but will not expect @@author FH-30``` to also be assigned to Anonymous.

If we change the type of ```TreeMap``` assigned to ```authorDetailsToAuthorMap```, ```@@author FH-30``` will be assigned to FH-30 and ```@@author fh-30``` will be assigned to Anonymous. Not to mention there will be no warning logged in this scenario.

However, there is still a scenario where the behavior of the current and fixed implementation can be odd as shown below:
1. Author with GithubId FH-30
2. Author with GithubId Anonymous and git name (alias) FH-30

Logged message:
```Duplicate alias FH-30 found. The alias will belong to the last author - Anonymous```

Now if the user of RepoSense sees the log message he'll understand why ```@@author FH-30``` will be assigned to Anonymous. But now consider that ```Anonymous``` and ```FH-30``` are taking ```CS2103T``` using the @@author feature of RepoSense. The students don't know anything about the author-config.csv nor about the log messages. Everytime ```FH-30``` writes code, he'll assign it to himself using @@author FH-30. However because of the same FH-30 alias of Anonymous, it'll be assigned to Anonymous instead.

We might need a way to handle cases where aliases and gitID's of different authors are the same to prevent such scenarios (i.e if the gitId of an author and the gitId/alias of another author is the same and vice versa). (Nothing comes to mind for now, maybe prof @damithc can give a suggestion if you think this is worth addressing)

Questions are welcome if this is still too deep into the details.

**Comment by damithc** [comment] 2021-07-30 18:22
Thanks for the detailed analysis @FH-30 

For the warning triggered by case sensitivity, perhaps the log message can be tweaked so that the reader will know it was cased by case sensitivity? e.g., mention both aliases in the log message so that reader can see that they are the same but different case. Is that possible, suitable?

Yes, detecting overlap of GitHub username and Git aliases can be useful.

**Comment by FH-30** [comment] 2021-07-30 19:00
As for the warning, I agree with you that it can be made clearer if both aliases are mentioned in it, however it wouldn't mitigate the scenario I cited above from happening. Nor will it give the user an idea of why it happened.

This odd behavior is due to this:
![Screen Shot 2021-07-31 at 2 55 14 AM](https://user-images.githubusercontent.com/61911161/127699169-8a911e4b-c5a2-49f8-b6de-d5966d7ff199.png)

If you notice the key "Hello" has its value altered without using a put method with "Hello" as a key.
Similarly, a gitId/githubId key might point to another author when a different cased gitId/githubId is encountered. (This results in a bug but the chances of it happening is slim)

**Comment by damithc** [comment] 2021-07-31 03:57
> As for the warning, I agree with you that it can be made clearer if both aliases are mentioned in it

Turns out the log message has both aliases already. I guess no further action is necessary.
However, I noticed in the example log messages above that even differences in symbols cause the log messages to appear? e.g., `wei yutong` vs `wei-yutong`

> If you notice the key "Hello" has its value altered without using a put method with "Hello" as a key.
> Similarly, a gitId/githubId key might point to another author when a different cased gitId/githubId (but same sequence of characters) is encountered.

This is an implementation detail, not part of the external behavior that we are discussing. Resist the urge to digress into implementation details. :-)

> This results in a bug with the @@author feature but the chances of it happening is slim.

Thanks for spotting this bug. Is it fixable? ~~How to fix?~~ How would the fix affect users? Implementation cost (i.e., complexity, effort)? We can leave it be if the cost is too high, given the incidence is very low.

BTW, isn't the possibility of the bug easily detectable through the data in the author-config file? i.e., if two people have similar identifiers, it should be apparent from the config file.

**Comment by FH-30** [comment] 2021-07-31 04:53
> However, I noticed in the example log messages above that even differences in symbols cause the log messages to appear? e.g., `wei yutong` vs `wei-yutong`
> 
> >

Yes, with the current implementation of RepoSense the logged warning is still confusing in a case like this. Why the warning occurs here is because how this author is declared in author-config.csv is as follows:
* Author with githubId wei-yutong and with gitIds(aliases) Wei Yutong and wei yutong.
Duplicates in aliases also trigger the warning as githubIds and gitIds are treated as the same (duplicates between any of them can trigger the warning). 
Here the warning is triggered because "Wei Yutong" is added first ("wei-yutong" is already recorded by RepoSense as githubIds are recorded first and gitIds are recorded from left to right) and is already recorded by RepoSense but due to the current "buggy" implementation when RepoSense encounters "wei yutong", "wei yutong".equals("Wei Yutong") is considered true so RepoSense thinks that "wei yutong" is already in the current record and therefore flags the warning.

> Turns out the log message has both aliases already. I guess no further action is necessary.

It doesn't have both aliases, it only indicates which alias is considered a duplicate but it does not indicate what it is a duplicate of, the other alias tagged is the author's gitId that the duplicated alias will be linked to. (however the current log message need not be altered if we perform the bug fix)

> Thanks for spotting this bug. Is it fixable? ~How to fix?~ How would the fix affect users? Implementation cost (i.e., complexity, effort)? We can leave it be if the cost is too high, given the incidence is very low.

It is a very simple fix, only involves altering one line (test code can be left intact). The fix will affect only the @@author functionality.

> BTW, isn't the possibility of the bug easily detectable through the data in the author-config file? i.e., if two people have similar identifiers, it should be apparent from the config file.

Yes but it isn't intuitive that two gitIds/githubIds are considered duplicates if they have different casing. Though I agree it can be eyeballed.

> This is an implementation detail, not part of the external behavior that we are discussing. Resist the urge to digress into implementation details. :-)

Right noted, sorry prof!

**Comment by damithc** [comment] 2021-07-31 05:31
> It is a very simple fix, only involves altering one line (test code can be left intact). The fix will affect only the @@author functionality.

@FH-30 From the user POV, how does the bug fix change the @@author behavior?

**Comment by FH-30** [comment] 2021-07-31 06:14
In ```author-config.csv``` if we add two authors:
1. Author with GithubId FH-30
2. Author with GithubId Anonymous and git name (alias) fh-30

The warning logged:
```Duplicate alias fh-30 found. The alias will belong to the last author - Anonymous```.

Now when this happens, whenever the repository consisting the two authors above are analyzed and the actual author FH-30 uses ```@@author FH-30``` wherever he writes code to mark it as his, it will be assigned to Anonymous instead.

Reading the warning logged also does not explain anything to the user because from the user's perspective, ```FH-30``` is different from ```fh-30``` so by reading the warning the user will only assume that ```@@author fh-30``` will be assigned to Anonymous but will not expect ```@@author FH-30``` to also be assigned to Anonymous.

If we make the bug fix, ```@@author FH-30``` will be assigned to FH-30 and ```@@author fh-30``` will be assigned to Anonymous. Not to mention there will be no warning logged in this scenario.

**Comment by damithc** [comment] 2021-07-31 06:22
> If we make the bug fix, `@@author FH-30` will be assigned to FH-30 and `@@author fh-30` will be assigned to Anonymous. Not to mention there will be no warning logged in this scenario.

Sounds good @FH-30. I was prepared to accept a better detection only but it seems we can actually fix the problem proper. I'm OK with the change to the external behavior. Perhaps create a PR so that senior devs can comment on the implementation?

**Comment by FH-30** [comment] 2021-07-31 06:25
Alright will do so, thanks for the feedback prof!

**Closed** 2021-08-22 07:15 UTC
Labels: c.Bug, p.Medium, c.Investigate
