### ISSUE TITLE
Collapsed chunks: cosmetic tweaks

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#34] opened 2018-03-23 09:40 UTC
![image](https://user-images.githubusercontent.com/1673303/37822191-bfc99c38-2ec0-11e8-8fcf-b7939e584733.png)

Collapsed chunks should not attract too much attention
Things to try:
*  Remove boarder
* Use grey, non-bold text
* Use a glyphicon or symbols instead of text e.g.,
  >← · · · →

**Comment by ongspxm** [comment] 2018-07-31 06:08
duplicate of #188

**Closed by ongspxm** 2018-07-31 06:08 UTC
Labels: a-UIX, p.Low
