### ISSUE TITLE
Tick boxes and expand/collapse button don't play well together

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#549] opened 2019-02-09 06:06 UTC
Ticking file types tick boxes (in particular, the `All` tick box) and expand/collapse button in tandem can result in inconsistent states. An example given below:

From https://nus-cs3281.github.io/2019-dashboard

![image](https://user-images.githubusercontent.com/1673303/52517242-7c502880-2c73-11e9-9512-c71f5713b364.png)

**Comment by yong24s** [comment] 2019-02-09 10:33
Duplicate of #521. 
Will resolve in PR #529. :-)

**Comment by fzdy1914** [comment] 2019-03-03 13:49
Close via #529

**Closed by fzdy1914** 2019-03-03 13:49 UTC
Labels: a-FrontEnd, c.Bug, p.Low
