### ISSUE TITLE
Reloading hides the display name in authorship contribution

### ISSUE THREAD

**Issue by HCY123902** [reposense/RepoSense#1455] opened 2021-02-15 05:29 UTC
**Tell us about your environment**

* **RepoSense Version:** master
* **OS and Version:** Windows10
* **Web Browser and Version (if applicable):** Edge

**Please include the steps to reproduce the bug.**

1. Open a generated report, select an anthor and view the authorship contribution
1. Refresh the page

**What was expected to happen?**
The display name should be shown along with the author name on the top left corner of the authorship contribution panel

**What actually happened? Please include a screenshot of the output.**
![image](https://user-images.githubusercontent.com/54735123/107908684-9d019600-6f91-11eb-98e8-c069f90a8820.png)

The display name is not shown. This is possibly related to #1223 

**If possible, include the URL to your RepoSense report or log files (if any).**

**Comment by dcshzj** [comment] 2021-02-15 05:47
I think this is a duplicate of #1446.

**Closed** 2021-02-15 06:09 UTC
Labels: c.Bug
