### ISSUE TITLE
Option to merge/map git-users

### ISSUE THREAD

**Issue by christophhalbi** [reposense/RepoSense#1788] opened 2022-06-15 07:09 UTC
**What feature(s) would you like to see in RepoSense?**

It would be quite useful to merge/map git-users of same origin to one user.

**Is the feature request related to a problem?**

Problem: the "same" (git-)user commits into the repo with different usernames like

```
Simon tester (tester)
simon (tester)
```

**If possible, describe the solution**

You could bring in an option to merge/map git usernames into one user.

**Comment by damithc** [comment] 2022-06-15 08:08
@christophhalbi Indeed, authors using different git usernames is a problem. The current remedy is to specify those different git usernames in the `Author's Git Author Name` of the author-config.csv https://reposense.org/ug/configFiles.html#author-config-csv after which RepoSense will consider all of them as one author and merge their activities together.
Is that along the lines of what you had in mind?

**Comment by christophhalbi** [comment] 2022-06-15 08:10
@damithc Thx! That looks great, I'll have a look.

**Comment by lawwm** [comment] 2022-09-26 15:33
I will be looking into this.

**Comment by lawwm** [comment] 2022-10-09 14:03
I've tried looking into the issue, but I'm not exactly sure what the problem is. It is possible that I missed out on something.

When I specify multiple `Author's Git Author Name` in the `author-config.csv`, it manages to merge them together into one author, so that method already works.

Is the issue then merging users when `author-config.csv` is not specified? In that case, `GitShortlog.getAuthors(config)` will be called instead, which means that git host id and display name will be the same.

**Comment by damithc** [comment] 2022-10-09 14:16
> Is the issue then merging users when `author-config.csv` is not specified?

@lawwm Yes, the proposed feature is an alternative (or can be complementary) to the current way of specifying multiple author names.

**Comment by lawwm** [comment] 2022-10-26 16:30
`GitShortlog.getAuthors(config)` is used to get author names, which runs `git log --pretty=short | git shortlog --summary` to get git usernames. An email flag `--email` can be added to `git shortlog` to include git email.

Maybe different usernames can be mapped to the same email? However, I'm not sure if it would be a useful feature?

**Comment by MarcusTXK** [comment] 2023-02-12 03:42
Currently, git has a nifty feature called [mailmap](https://git-scm.com/docs/gitmailmap). By specifying a `.mailmap` file in the top level of the repository, it allows a user to map author/commiter names and/or e-mail addresses.

After some investigation, it seems this feature already innately works, and no modification of RepoSense backend is required. It also seems to have priority over any mappings done by `author-config.csv`. I think that we can add some documentation about the option to use git's mailmap feature and close this issue.

### Before
![image](https://user-images.githubusercontent.com/50147457/218291677-15bf799a-c70c-48c7-95c6-20651d217d23.png)

### After adding `.mailmap` file
.mailmap:
```
Marcus Tang <txk.marcus@gmail.com> Marcus <txk.marcus@gmail.com>
```
![image](https://user-images.githubusercontent.com/50147457/218291678-9b2b6efc-c76b-462e-8763-649ed863dd05.png)

**Comment by chan-j-d** [comment] 2023-02-12 08:30
Thanks for the investigation. That's really interesting. Maybe under this section of the UG https://reposense.org/ug/customizingReports.html#get-target-repos-to-provide-more-info

**Closed** 2023-03-15 03:26 UTC
Labels: c.Feature, a-Backend
