### ISSUE TITLE
RampChart: Ramp URL lead to 404 web page on github when analyzing a local Repo

### ISSUE THREAD

**Issue by fzdy1914** [reposense/RepoSense#491] opened 2019-01-19 05:27 UTC
When analyzing the local Repo, the ramp in the ramp chart will lead to a non-existing web page.

**Comment by yong24s** [comment] 2019-01-19 16:35
Took me a while to find the issue.

Duplicate of #231

**Closed** 2019-01-19 16:37 UTC
Labels: a-Backend, a-FrontEnd, c.Bug
