### ISSUE TITLE
Code view: differentiate fully-owned code from jointly-owned code

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#462] opened 2019-01-07 12:06 UTC
Current: All code attributed to the author is shown in the same way

Suggested: Distinguish between fully-owned code (i.e., no other person has touched that code) from jointly-owned code (i.e., multiple authors have touched that code).

**Comment by ckcherry23** [comment] 2023-12-11 06:28
Closing this issue as a duplicate of #944 which provides more implementation details.

**Closed** 2023-12-11 06:28 UTC
Labels: p.High, c.Feature
