### ISSUE TITLE
Code view: follow file group selection of the ramp chart

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#1253] opened 2020-04-22 06:22 UTC
When a user clicks on a `</>` to open a code view, if a certain file group selection has already been made in the ramp chart view, it's better for the code view to follow the same selection automatically.

**Comment by Tejas2805** [comment] 2020-04-22 11:04
Duplicate of #1150 . PR #1152 is solving this issue.

**Closed by Tejas2805** 2020-04-22 11:04 UTC
Labels: c.Feature, p.Medium
