### ISSUE TITLE
Weird highlighting of commits in commits panel

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#1180] opened 2020-03-24 09:45 UTC
This occurs when the commits take up more than one line (buttons, tags and everything included).

![image](https://user-images.githubusercontent.com/35756209/77411228-09622c80-6df7-11ea-9db6-12b0427dee97.png)

To replicate: go to commits panel, and click on any commits that take up more than one line when commit message body is collapsed.

**Comment by jamessspanggg** [comment] 2020-03-24 15:11
Note that this issue only occurs for chrome but not safari

**Comment by Boon-Jun** [comment] 2020-08-17 11:30
Can someone help me verify whether if the weird highlighting is still a problem? I've tried on multiple browsers(chrome included) and i'm unable to replicate this issue.

**Comment by Tejas2805** [comment] 2020-08-17 19:11
> Can someone help me verify whether if the weird highlighting is still a problem? I've tried on multiple browsers(chrome included) and i'm unable to replicate this issue.

Looks like, after the most recent update of google chrome, this issue is fixed. Can't seem to replicate it too.

@jamessspanggg @fzdy1914 Can either of you confirm too. Then we can go-ahead with closing the issue.

**Comment by fzdy1914** [comment] 2020-08-18 07:49
Can't reproduce also, closing it.

**Closed by fzdy1914** 2020-08-18 07:49 UTC
Labels: a-FrontEnd, c.Bug, p.Low
