### ISSUE TITLE
Clicking on ramps in ramp chart generated using local repos redirects to non-existent link

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#231] opened 2018-07-23 10:58 UTC
Following #210, the clicking on ramps in ramp chart generated using local repos will redirect user to non-existence link. This is because local repository lacks organization info.

Let's fix this by making the links redirect to the correct remote repository if the remote url can be found in the local repository, otherwise make it non-clickable.

**Note: an alternative solution is to show the commits info locally in the dashboard instead of redirecting to GitHub repo.

**Comment by yong24s** [comment] 2018-07-23 23:51
Duplicate of #230. Will close #230.

**Comment by yong24s** [comment] 2019-01-19 16:39
Useful git command to test if local repository is cloned from a remote one -- 
`git remote get-url origin`

**Closed** 2022-04-14 01:05 UTC
Labels: p.Medium, a-FrontEnd
