### ISSUE TITLE
Weird line number in chartView when break down by file type

### ISSUE THREAD

**Issue by 0blivious** [reposense/RepoSense#1236] opened 2020-04-16 08:27 UTC
As shown below
![image](https://user-images.githubusercontent.com/39231750/79432610-a4b57e80-7ffe-11ea-8b21-3121ab3ec548.png)

The doc type icon is displayed even the LoC is 0. Also, the group did have some contribution in adoc in the commit https://github.com/reposense/testrepo-Delta/commit/588963c9e80c35a765753837618b4b32b7aa11dc

**Comment by jamessspanggg** [comment] 2020-04-16 14:43
> The doc type icon is displayed even the LoC is 0. 

We display the docs file type even though LoC is 0, this is because within `group-config.csv`, the types `code`, `tests` and `docs` were specifically listed.

> Also, the group did have some contribution in adoc in the commit reposense/testrepo-Delta@588963c

Not so sure about this. Perhaps can investigate further?

**Comment by jamessspanggg** [comment] 2020-04-16 15:25
> Also, the group did have some contribution in adoc in the commit reposense/testrepo-Delta@588963c

<img width="991" alt="Screen Shot 2020-04-16 at 11 24 35 PM" src="https://user-images.githubusercontent.com/32864116/79474823-7903ba00-8039-11ea-9690-b9ea457a4d54.png">

It is due to our `repo-config.csv`, only analysing files with the extensions `.java` and `.md`. The commits that you shown were `.adoc` files.

**Comment by jamessspanggg** [comment] 2020-04-16 15:29
Closing this, as it is intentional and not a bug.

**Closed by jamessspanggg** 2020-04-16 15:29 UTC
Labels: c.Investigate
