### ISSUE TITLE
Surge.sh previews are no longer working

### ISSUE THREAD

**Issue by sikai00** [reposense/RepoSense#1964] opened 2023-03-27 02:40 UTC
### Tell us about your environment

* **RepoSense Version:** N/A
* **OS and Version:** MacOs 13.2.1
* **Web Browser and Version (if applicable):** Chrome 111.0.5563.110

### Please include the steps to reproduce the bug.

At a certain point in the last few days, surge.sh previews seems to have stopped working for new PRs.

Example: https://docs-1961-pr-reposense-reposense.surge.sh/ in #1961.

### What was expected to happen?

There should be a surge.sh preview showing RepoSense and its documentation for PRs.

### What actually happened? Please include a screenshot of the output.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/63795894/227826984-16f6378c-a7df-46d8-8ddc-ce80be204e90.png">

I believe this issue may have been caused by the upgrading of Node.js version to 16 in a recent PR #1956. This issue has previously happened before in #1374, and was resolved in #1381. We can possibly look into a similar approach to resolve this issue. Do note that there are differences, 1) being that Travis was used before, 2) both documentation and dashboard previews are no longer working instead of just documentation.

**Comment by ckcherry23** [comment] 2023-03-27 06:52
This may be unrelated, but dashboard previews for #1939 have not been updating with the latest changes since last Monday, despite repeated deployments. 

Noting that issue here in case they do have the same root cause.
If not, will file a separate bug report for it later.

**Comment by yhtMinceraft1010X** [comment] 2023-03-31 15:06
Maybe we could try switching to Netlify for our pull request previews. Has Netlify been used before? If so, why did we switch to Surge?

**Comment by yhtMinceraft1010X** [comment] 2023-04-16 02:35
<img width="412" alt="image" src="https://user-images.githubusercontent.com/69678785/232262924-635b2cd5-3ce9-40c8-889c-7c17cab4a052.png">

I noticed that there is a message about invalid tokens, so I think regenerating `secrets.SURGE_LOGIN` and/or `secrets.SURGE_TOKEN` might help, but I'm not sure exactly where they are stored:
https://github.com/reposense/RepoSense/blob/7a58117a78c2432cea116871a7ce5c37abe6409c/.github/workflows/surge.yml#L59-L64

If anyone knows, pls do not mention it here but on our private communications channels.

**Comment by yhtMinceraft1010X** [comment] 2023-05-12 16:01
I re-ran a build preview for #1999 just now. It seems to work since the documentation changes are reflected in the preview: https://docs-1999-pr-reposense-reposense.surge.sh/dg/report.html

Will close this issue as I assume it has been fixed by regenerating the token.

**Closed by yhtMinceraft1010X** 2023-05-12 16:01 UTC
Labels: c.Bug, p.High, a-DevOps, c.Investigate
