### ISSUE TITLE
Give a way to find repos with a specific tag

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#2109] opened 2024-02-12 18:42 UTC
Suggestion: enhance the search feature to find repos with a specific tag e.g, `tag:A-JUnit`
![image](https://github.com/reposense/RepoSense/assets/1673303/06496210-5d4b-4566-a5d4-5a8aee9a312c)

This is a niche use case but could be useful for courses such as CS2103, for students/instructors to easily find repos which has a specific tag

Not sure how hard it is to implement though.

**Comment by ckcherry23** [comment] 2024-03-20 10:35
@jonasongg Based on the issue reported in #2164, can you investigate what went wrong and reopen a PR for this?

To the RepoSense team: 
Although the merged PR successfully implemented the required search-by-tag functionality with adequate test cases, it inadvertently broke unrelated functionality. This oversight occurred because the data seemed to be intended that way, leading to its unnoticed impact.

This is because our end-to-end tests mainly focus on testing features rather than data representation. To avoid this in the future, we could do the following:
* Data-driven testing: Add tests to check if the actual JSON data is being represented in the expected manner.
* Snapshot testing: Implement snapshot testing to ensure there are no visual regressions.

**Comment by jonasongg** [comment] 2024-03-21 15:43
@ckcherry23 I just investigated this and think I found what is causing the bug. How should I reopen a PR for this fix - should I push to the same branch as I did originally and keep the commit message the same (including the fact that it includes a bug fix)?

As for how to include different testing techniques for our frontend, maybe it'd be best to discuss in-person on Monday with the rest of the team!

**Comment by ckcherry23** [comment] 2024-03-22 05:55
> @ckcherry23 I just investigated this and think I found what is causing the bug. How should I reopen a PR for this fix - should I push to the same branch as I did originally and keep the commit message the same (including the fact that it includes a bug fix)?

@jonasongg Yes, you can push to the same branch as the merge commit was fully reverted. You can keep the commit message the same (and add the bug fix part if needed).

**Closed** 2024-04-01 18:51 UTC
Labels: c.Feature, s.ToDiscuss
